# P1 Source-Aware Dual Loss config for PASAM PNet.
#
# P0:
#   Full GT + weak pseudo -> unified NCLoss
#
# P1:
#   Full GT     -> StructureLoss
#   Weak pseudo -> NCLoss
#   L_mask      -> 0.5 * L_full + 0.5 * L_weak (with default 1:1 source weights)
#
# Network, Edge loss, UAL, data split, batch sizes, optimizer and scheduler
# are intentionally kept unchanged for a clean ablation.

has_test = True
deterministic = True
use_custom_worker_init = True
log_interval = 20
base_seed = 112358

model = dict(
    channels=64,
    ual_weight=2.0,

    # P1 switch
    source_aware_loss=True,

    # clean GT branch
    full_loss_type="structure",

    # noisy ANet pseudo branch
    weak_loss_type="nc",

    # source-level balancing:
    # (1 * L_full + 1 * L_weak) / 2
    full_loss_weight=1.0,
    weak_loss_weight=1.0,

    # pred0 / p4 / p3 / p2 / p1
    mask_level_weights=(
        0.0625,
        0.125,
        0.25,
        0.5,
        1.0,
    ),
)

train = dict(
    # Must match the ANet fully-labelled split.
    full_ratio=0.01,
    split_seed=112358,

    # Generated by anet_main.py --generate.
    pseudo_mask_root="outputs/ANet_F20/30/pseudo_mask",
    pseudo_edge_root="outputs/ANet_F20/30/pseudo_edge",
    pseudo_suffix=".png",

    # Keep P0 batch protocol unchanged.
    batchsize_fully=2,
    batchsize_weakly=8,
    
    num_workers=4,
    use_amp=True,
    

    num_epochs=100,

    # In P1 q only affects the weak NCLoss branch.
    q_epoch=60,

    # Keep current P0 behavior for fair comparison.
    steps_mode="use_all_weak",

    augment=True,

    lr=1e-4,
    grad_acc_step=1,

    optimizer=dict(
        mode="adam",
        set_to_none=False,
        group_mode="finetune",
        cfg=dict(
            weight_decay=0,
            diff_factor=1.0,
        ),
    ),

    # Keep the current P0 scheduler unchanged for this ablation.
    sche_usebatch=True,
    scheduler=dict(
        warmup=dict(
            num_iters=0,
            initial_coef=0.01,
            mode="linear",
        ),
        mode="step",
        cfg=dict(
            milestones="auto",
            gamma=0.1,
        ),
    ),

    val_start_epoch=10,
    val_interval=5,
    save_val_ckpt=True,

    data=dict(
        shape=dict(h=384, w=384),
        names=["combined_tr"],
    ),
)

test = dict(
    batch_size=16,
    num_workers=8,
    clip_range=None,
    data=dict(
        shape=dict(h=384, w=384),
        names=[
            "chameleon",
            "camo_te",
            "cod10k_te",
            "nc4k",
        ],
    ),
)
