# Noisy-COD PNet config adapted to WS_SAM_CL.

has_test = True
deterministic = True
use_custom_worker_init = True
log_interval = 20
base_seed = 112358

model = dict(
    channels=64,
    ual_weight=2.0,
    deep_weight = 0.5,
    edge_weight = 0.5
)

train = dict(
    # IMPORTANT: must match the ANet fully-labelled split.
    clean_list="data/pseudo_pool/shape/clean.txt",
    full_ratio=0.2,
    split_seed=112358,

    # Generated by anet_main.py --generate.
    # Set this to the exact exp directory produced by your ANet.
    # The ANet patch writes generated labels under cfg.path.output_dir,
    # so with --output-dir ANet_outputs these are:
    pseudo_mask_root="ANet_outputs/S1/pseudo_mask",
    pseudo_edge_root="ANet_outputs/S1/pseudo_edge",
    pseudo_suffix=".png",

    # Official PNet defaults use a real-GT anchor batch + larger weak batch.
    batchsize_fully=6,
    batchsize_weakly=24,
    num_workers=4,
    use_amp=True,

    num_epochs=100,
    steps_per_epoch=166,

    # Released TrainDDP.py defaults to q_epoch=60.
    # q=2 before/at this epoch; q=1 afterwards.
    q_epoch=60,

    # "official_min" exactly follows zip(fully_loader, weak_loader):
    # steps = min(len(full_loader), len(weak_loader)).
    #
    # "use_all_weak" cycles the small full loader and consumes all weak
    # pseudo-label samples every epoch; this is useful for ablations but is
    # NOT the exact released schedule.
    steps_mode = "use_all_weak",

    augment=True,

    lr=1e-4,
    grad_acc_step=1,

    optimizer=dict(
        mode="adam",
        set_to_none=False,
        group_mode="finetune",
        cfg=dict(
            weight_decay=0,
            # Official PNet uses same Adam LR for the whole network.
            diff_factor=1.0,
        ),
    ),

    sche_usebatch=True,
    scheduler=dict(
        warmup=dict(
            num_iters=0,
            initial_coef=0.01,
            mode="linear",
        ),
        mode="step",
        cfg=dict(
            # Can tune later; this is a safe WS_SAM_CL-style starting point.
            milestones="auto",
            gamma=0.1,
        ),
    ),

    val_start_epoch=10,
    val_interval=5,
    save_val_ckpt=True,

    data=dict(
        shape=dict(h=384, w=384),
        names=["combined_tr"],
    ),
)

test = dict(
    batch_size=16,
    num_workers=8,
    clip_range=None,
    data=dict(
        shape=dict(h=384, w=384),
        names=[
            "chameleon",
            "camo_te",
            "cod10k_te",
            "nc4k",
        ],
    ),
)
